// constants/Agents.constants.ts

import { IAgent, IProviderOption, IServiceOption, ISortOption, IStatusOption } from "../types/searchAgentTypes";


export const DUMMY_AGENTS: IAgent[] = [
  {
    id: '1',
    name: 'Agent 1',
    address: 'Oxford St',
    latitude: 5.6037,
    longitude: -0.1870,
    distance: 0.2,
    status: 'open',
    services: ['cash_in', 'cash_out'],
    provider: 'mtn',
    rating: 4.5,
    cashAvailable: true,
    phone: '+233-24-123-4567',
    workingHours: '8:00 AM - 6:00 PM',
    transactions: 1250,
    joinedDate: '2023-01-15',
  },
  {
    id: '2',
    name: 'Kwame\'s Mobile Money',
    address: 'Nkrumah Circle',
    latitude: 5.5744,
    longitude: -0.2168,
    distance: 0.5,
    status: 'open',
    services: ['cash_in', 'cash_out', 'airtime'],
    provider: 'vodafone',
    rating: 4.8,
    cashAvailable: true,
    phone: '+233-26-987-6543',
    workingHours: '7:00 AM - 8:00 PM',
    transactions: 2850,
    joinedDate: '2022-08-20',
  },
  {
    id: '3',
    name: 'Akosua MoMo Point',
    address: 'Madina Market',
    latitude: 5.6839,
    longitude: -0.1677,
    distance: 0.8,
    status: 'closed',
    services: ['cash_in'],
    provider: 'airteltigo',
    rating: 4.2,
    cashAvailable: false,
    phone: '+233-27-456-7890',
    workingHours: '9:00 AM - 5:00 PM',
    transactions: 890,
    joinedDate: '2023-03-10',
  },
  {
    id: '4',
    name: 'Quick Cash Services',
    address: 'Accra Mall',
    latitude: 5.6238,
    longitude: -0.1759,
    distance: 1.2,
    status: 'open',
    services: ['cash_in', 'cash_out', 'bill_payment'],
    provider: 'mtn',
    rating: 4.9,
    cashAvailable: true,
    phone: '+233-24-111-2222',
    workingHours: '24/7',
    transactions: 4200,
    joinedDate: '2022-05-05',
  },
  {
    id: '5',
    name: 'Kojo Cash Services',
    address: 'East Legon',
    latitude: 5.6238,
    longitude: -0.1759,
    distance: 1.5,
    status: 'open',
    services: ['cash_in', 'cash_out', 'bill_payment'],
    provider: 'mtn',
    rating: 4.6,
    cashAvailable: true,
    phone: '+233-24-333-4444',
    workingHours: '8:00 AM - 10:00 PM',
    transactions: 1800,
    joinedDate: '2023-02-14',
  },
  {
    id: '6',
    name: 'Ponj Cash Services',
    address: 'Tema Station',
    latitude: 5.6238,
    longitude: -0.1759,
    distance: 2.1,
    status: 'busy',
    services: ['cash_in', 'cash_out', 'bill_payment'],
    provider: 'vodafone',
    rating: 4.3,
    cashAvailable: true,
    phone: '+233-26-555-6666',
    workingHours: '6:00 AM - 9:00 PM',
    transactions: 2100,
    joinedDate: '2022-11-30',
  },
  {
    id: '7',
    name: 'Omar Cash Services',
    address: 'Kaneshie Market',
    latitude: 5.6238,
    longitude: -0.1759,
    distance: 2.8,
    status: 'open',
    services: ['cash_in', 'cash_out', 'bill_payment', 'airtime'],
    provider: 'mtn',
    rating: 4.7,
    cashAvailable: true,
    phone: '+233-24-777-8888',
    workingHours: '7:00 AM - 7:00 PM',
    transactions: 3200,
    joinedDate: '2022-09-18',
  },
  {
    id: '8',
    name: 'Wendy Cash Services',
    address: 'Osu Oxford Street',
    latitude: 5.6238,
    longitude: -0.1759,
    distance: 1.8,
    status: 'open',
    services: ['cash_in', 'cash_out'],
    provider: 'airteltigo',
    rating: 4.4,
    cashAvailable: true,
    phone: '+233-27-999-0000',
    workingHours: '8:00 AM - 6:00 PM',
    transactions: 1450,
    joinedDate: '2023-01-22',
  },
  {
    id: '9',
    name: 'Ashley Cash Services',
    address: 'Lapaz New Market',
    latitude: 5.6238,
    longitude: -0.1759,
    distance: 3.2,
    status: 'closed',
    services: ['cash_in', 'cash_out', 'bill_payment'],
    provider: 'mtn',
    rating: 4.1,
    cashAvailable: false,
    phone: '+233-24-123-9999',
    workingHours: '9:00 AM - 5:00 PM',
    transactions: 980,
    joinedDate: '2023-04-03',
  },
];

export const SORT_OPTIONS: ISortOption[] = [
  { key: 'distance', label: 'Distance', icon: 'near-me' },
  { key: 'rating', label: 'Rating', icon: 'star' },
  { key: 'name', label: 'Name', icon: 'sort-by-alpha' },
  { key: 'Pins', label: 'Popularity', icon: 'trending-up' },
  { key: 'joinedDate', label: 'Newest', icon: 'schedule' },
];

export const PROVIDER_OPTIONS: IProviderOption[] = [
  { key: 'all', label: 'All Networks', color: '#9E9E9E' },
  { key: 'mtn', label: 'MTN', color: '#FFCC00' },
  { key: 'vodafone', label: 'Vodafone', color: '#E60000' },
  { key: 'airteltigo', label: 'AirtelTigo', color: '#FF0066' },
];

export const STATUS_OPTIONS: IStatusOption[] = [
  { key: 'all', label: 'All Status', color: '#9E9E9E' },
  { key: 'open', label: 'Open', color: '#4CAF50' },
  { key: 'closed', label: 'Closed', color: '#F44336' },
  { key: 'busy', label: 'Busy', color: '#FF9800' },
];

export const SERVICE_OPTIONS: IServiceOption[] = [
  { key: 'all', label: 'All Services' },
  { key: 'cash_in', label: 'Cash In' },
  { key: 'cash_out', label: 'Cash Out' },
  { key: 'bill_payment', label: 'Bill Payment' },
  { key: 'airtime', label: 'Airtime' },
];

export const REFRESH_TIMEOUT = 2000;