import { colors } from '../constants/theme/colors';
import { IActivitiesData, IAgent, IDashboardData, IIntroSlide, INotification, IProduct, IVendorStats } from '../types';

export const dummyAgents: IAgent[] = [
  {
    id: '1',
    name: 'Agent 1',
    address: 'Çark Caddesi',
    latitude: 40.7833,
    longitude: 30.4034,
    distance: 0.2,
    status: 'open',
    services: ['cash_in', 'cash_out'],
    provider: 'mtn',
    rating: 4.5,
    cashAvailable: true,
  },
  {
    id: '2',
    name: 'Kwame\'s Mobile Money',
    address: 'Serdivan AVM',
    latitude: 40.7545,
    longitude: 30.3891,
    distance: 0.5,
    status: 'open',
    services: ['cash_in', 'cash_out', 'airtime'],
    provider: 'vodafone',
    rating: 4.8,
    cashAvailable: true,
  },
  {
    id: '3',
    name: 'Akosua MoMo Point',
    address: 'Adapazarı Terminal',
    latitude: 40.7740,
    longitude: 30.3975,
    distance: 0.8,
    status: 'closed',
    services: ['cash_in'],
    provider: 'airteltigo',
    rating: 4.2,
    cashAvailable: false,
  },
  {
    id: '4',
    name: 'Quick Cash Services',
    address: 'Donatım Park',
    latitude: 40.7812,
    longitude: 30.3901,
    distance: 1.2,
    status: 'open',
    services: ['cash_in', 'cash_out', 'bill_payment'],
    provider: 'mtn',
    rating: 4.9,
    cashAvailable: true,
  },
  {
    id: '5',
    name: 'Kojo Cash Services',
    address: 'Kentpark AVM',
    latitude: 40.7649,
    longitude: 30.3905,
    distance: 1.2,
    status: 'open',
    services: ['cash_in', 'cash_out', 'bill_payment'],
    provider: 'mtn',
    rating: 4.9,
    cashAvailable: true,
  },
  {
    id: '6',
    name: 'Ponj Cash Services',
    address: 'Yenikent Bölgesi',
    latitude: 40.7871,
    longitude: 30.4260,
    distance: 1.2,
    status: 'open',
    services: ['cash_in', 'cash_out', 'bill_payment'],
    provider: 'mtn',
    rating: 4.9,
    cashAvailable: true,
  },
  {
    id: '7',
    name: 'Omar Cash Services',
    address: 'Sakarya University Main Gate',
    latitude: 40.7419,
    longitude: 30.3343,
    distance: 1.2,
    status: 'open',
    services: ['cash_in', 'cash_out', 'bill_payment'],
    provider: 'mtn',
    rating: 4.9,
    cashAvailable: true,
  },
  {
    id: '8',
    name: 'Wendy Cash Services',
    address: 'Sakarya Eğitim ve Araştırma Hastanesi',
    latitude: 40.7745,
    longitude: 30.3707,
    distance: 1.2,
    status: 'open',
    services: ['cash_in', 'cash_out', 'bill_payment'],
    provider: 'mtn',
    rating: 4.9,
    cashAvailable: true,
  },
  {
    id: '9',
    name: 'Ashley Cash Services',
    address: 'Karaman Mahallesi',
    latitude: 40.7608,
    longitude: 30.4130,
    distance: 1.2,
    status: 'open',
    services: ['cash_in', 'cash_out', 'bill_payment'],
    provider: 'mtn',
    rating: 4.9,
    cashAvailable: true,
  },
];

// Activity data
export const activitiesData: IActivitiesData = {
  totalActivities: 234,
  todayActivities: 15,
  thisWeekActivities: 89,
  activities: [
    {
      id: 'act1',
      type: 'transaction',
      category: 'financial',
      title: 'Cash Out Transaction',
      description: 'Withdrew GH₵ 150.00 from Johnson Mobile Money',
      amount: 'GH₵ 150.00',
      agent: 'Johnson Mobile Money',
      agentAvatar: 'https://i.pravatar.cc/150?img=9',
      timestamp: '2025-05-26T14:30:00Z',
      status: 'completed',
      icon: 'arrow-upward',
      iconColor: colors.error,
      transactionId: 'TXN123456789'
    },
    {
      id: 'act2',
      type: 'social',
      category: 'social',
      title: 'New Post Like',
      description: 'Emma Wilson liked your post about mobile money tips',
      user: 'Emma Wilson',
      userAvatar: 'https://i.pravatar.cc/150?img=1',
      timestamp: '2025-05-26T13:45:00Z',
      status: 'new',
      icon: 'favorite',
      iconColor: colors.error,
      postId: 'post123'
    },
    {
      id: 'act3',
      type: 'transaction',
      category: 'financial',
      title: 'Bill Payment',
      description: 'Paid ECG electricity bill',
      amount: 'GH₵ 85.50',
      vendor: 'ECG Ghana',
      timestamp: '2025-05-26T12:20:00Z',
      status: 'completed',
      icon: 'receipt',
      iconColor: colors.accent,
      billNumber: 'ECG-2025-001234'
    },
    {
      id: 'act4',
      type: 'social',
      category: 'social',
      title: 'New Follower',
      description: 'James Miller started following you',
      user: 'James Miller',
      userAvatar: 'https://i.pravatar.cc/150?img=2',
      timestamp: '2025-05-26T11:15:00Z',
      status: 'new',
      icon: 'person-add',
      iconColor: colors.accent,
      userId: 'user456'
    },
    {
      id: 'act5',
      type: 'account',
      category: 'account',
      title: 'Profile Updated',
      description: 'Updated your profile picture and bio information',
      timestamp: '2025-05-26T10:30:00Z',
      status: 'completed',
      icon: 'person',
      iconColor: colors.primary
    },
    {
      id: 'act6',
      type: 'transaction',
      category: 'financial',
      title: 'Airtime Purchase',
      description: 'Bought MTN airtime',
      amount: 'GH₵ 20.00',
      vendor: 'MTN Ghana',
      timestamp: '2025-05-26T09:45:00Z',
      status: 'completed',
      icon: 'phone',
      iconColor: colors.primary,
      phoneNumber: '+233 24 xxx xxxx'
    },
    {
      id: 'act7',
      type: 'social',
      category: 'social',
      title: 'Post Comment',
      description: 'Sophie Chen commented on your financial tips post',
      user: 'Sophie Chen',
      userAvatar: 'https://i.pravatar.cc/150?img=3',
      timestamp: '2025-05-26T08:30:00Z',
      status: 'new',
      icon: 'chat-bubble',
      iconColor: colors.accent,
      comment: 'Great tips! Very helpful for beginners.'
    },
    {
      id: 'act8',
      type: 'system',
      category: 'system',
      title: 'Security Alert',
      description: 'Login from new device detected - iPhone 15',
      timestamp: '2025-05-26T07:20:00Z',
      status: 'warning',
      icon: 'security',
      iconColor: colors.warning,
      device: 'iPhone 15',
      location: 'Accra, Ghana'
    },
    {
      id: 'act9',
      type: 'transaction',
      category: 'financial',
      title: 'Money Transfer',
      description: 'Sent money to Maria Garcia',
      amount: 'GH₵ 100.00',
      recipient: 'Maria Garcia',
      recipientAvatar: 'https://i.pravatar.cc/150?img=5',
      timestamp: '2025-05-25T19:45:00Z',
      status: 'completed',
      icon: 'send',
      iconColor: colors.accent,
      transferId: 'TRF987654321'
    },
    {
      id: 'act10',
      type: 'social',
      category: 'social',
      title: 'New Review',
      description: 'You received a 5-star review from David Brown',
      user: 'David Brown',
      userAvatar: 'https://i.pravatar.cc/150?img=4',
      timestamp: '2025-05-25T18:30:00Z',
      status: 'new',
      icon: 'star',
      iconColor: colors.primary,
      rating: 5,
      review: 'Excellent service! Very professional and fast.'
    },
    {
      id: 'act11',
      type: 'agent',
      category: 'business',
      title: 'Agent Status Update',
      description: 'Changed your business status to "Available"',
      timestamp: '2025-05-25T17:15:00Z',
      status: 'completed',
      icon: 'business',
      iconColor: colors.success
    },
    {
      id: 'act12',
      type: 'transaction',
      category: 'financial',
      title: 'Data Bundle Purchase',
      description: 'Purchased 5GB data bundle',
      amount: 'GH₵ 15.00',
      vendor: 'MTN Ghana',
      timestamp: '2025-05-25T16:20:00Z',
      status: 'completed',
      icon: 'wifi',
      iconColor: colors.accent,
      dataAmount: '5GB'
    },
    {
      id: 'act13',
      type: 'social',
      category: 'social',
      title: 'Post Shared',
      description: 'Alex Johnson shared your mobile money safety tips',
      user: 'Alex Johnson',
      userAvatar: 'https://i.pravatar.cc/150?img=6',
      timestamp: '2025-05-25T15:45:00Z',
      status: 'new',
      icon: 'share',
      iconColor: colors.primary,
      shareCount: 12
    },
    {
      id: 'act14',
      type: 'system',
      category: 'system',
      title: 'App Update',
      description: 'MoMo Connect app updated to version 2.1.5',
      timestamp: '2025-05-25T14:00:00Z',
      status: 'info',
      icon: 'system-update',
      iconColor: colors.accent,
      version: '2.1.5'
    },
    {
      id: 'act15',
      type: 'achievement',
      category: 'gamification',
      title: 'Achievement Unlocked',
      description: 'Earned "Trusted Trader" badge for 100+ successful transactions',
      timestamp: '2025-05-25T12:30:00Z',
      status: 'achievement',
      icon: 'emoji-events',
      iconColor: colors.primary,
      badge: 'Trusted Trader',
      milestone: 100
    }
  ]
};

export const vendorStats: IVendorStats = {
  dailyCashIn: 5250.00,
  dailyCashOut: 3800.00,
  totalCustomers: 47,
  averageTransaction: 195.00,
  weeklyData: [
    { day: 'Mon', cashIn: 4200, cashOut: 3100 },
    { day: 'Tue', cashIn: 5100, cashOut: 3900 },
    { day: 'Wed', cashIn: 5250, cashOut: 3800 },
    { day: 'Thu', cashIn: 4800, cashOut: 4200 },
    { day: 'Fri', cashIn: 6200, cashOut: 5100 },
    { day: 'Sat', cashIn: 7500, cashOut: 6300 },
    { day: 'Sun', cashIn: 3200, cashOut: 2400 },
  ],
};

// Mock dashboard data - In real app, this would come from API
export const dashboardData: IDashboardData = {
  overview: {
    totalProducts: 24,
    activeProducts: 21,
    draftProducts: 3,
    totalViews: 15740,
    totalInquiries: 287,
    totalFavorites: 456,
    agentVisits: 124,
    conversionRate: 1.8,
    averageViewTime: '2m 18s',
    revenueThisMonth: 8450,
    growthRate: 12.3,
  },
  trends: {
    views: [1200, 1450, 1380, 1820, 1690, 2040, 2280],
    inquiries: [18, 25, 22, 34, 28, 41, 45],
    revenue: [850, 920, 780, 1240, 1150, 1380, 1520],
  },
  topProducts: [
    {
      id: 1,
      title: 'iPhone 13 Pro Max 256GB',
      image: 'https://picsum.photos/100/100?random=1',
      views: 2340,
      inquiries: 45,
      favorites: 89,
      price: 3200,
      status: 'active',
      trend: 15.2,
    },
    {
      id: 2,
      title: 'Samsung Galaxy S24 Ultra',
      image: 'https://picsum.photos/100/100?random=2',
      views: 1890,
      inquiries: 38,
      favorites: 67,
      price: 2800,
      status: 'active',
      trend: 8.7,
    },
    {
      id: 3,
      title: 'MacBook Air M2 512GB',
      image: 'https://picsum.photos/100/100?random=3',
      views: 1567,
      inquiries: 29,
      favorites: 54,
      price: 4500,
      status: 'active',
      trend: -2.1,
    },
    {
      id: 4,
      title: 'iPad Pro 11" 128GB',
      image: 'https://picsum.photos/100/100?random=4',
      views: 1234,
      inquiries: 24,
      favorites: 43,
      price: 2100,
      status: 'active',
      trend: 22.4,
    },
  ],
  categories: [
    { name: 'Phones', count: 8, views: 6240, color: '#FF6B6B', percentage: 33.3 },
    { name: 'Laptops', count: 5, views: 4320, color: '#4ECDC4', percentage: 20.8 },
    { name: 'Tablets', count: 4, views: 2180, color: '#45B7D1', percentage: 16.7 },
    { name: 'Accessories', count: 3, views: 1890, color: '#96CEB4', percentage: 12.5 },
    { name: 'Gaming', count: 2, views: 890, color: '#FFEAA7', percentage: 8.3 },
    { name: 'Audio', count: 2, views: 720, color: '#DDA0DD', percentage: 8.3 },
  ],
  recentActivity: [
    { id: 1, type: 'inquiry', product: 'iPhone 13 Pro Max', time: '2 min ago', user: 'John Doe' },
    { id: 2, type: 'view', product: 'Samsung Galaxy S24', time: '5 min ago', user: 'Jane Smith' },
    { id: 3, type: 'favorite', product: 'MacBook Air M2', time: '12 min ago', user: 'Mike Johnson' },
    { id: 4, type: 'inquiry', product: 'iPad Pro 11"', time: '18 min ago', user: 'Sarah Wilson' },
    { id: 5, type: 'visit', product: 'iPhone 13 Pro Max', time: '25 min ago', user: 'Agent phone viewed' },
  ],
  geography: [
    { region: 'Accra', products: 8, views: 5240, inquiries: 98, percentage: 33.2 },
    { region: 'Kumasi', products: 6, views: 3890, inquiries: 74, percentage: 24.7 },
    { region: 'Tamale', products: 4, views: 2340, inquiries: 45, percentage: 14.9 },
    { region: 'Cape Coast', products: 3, views: 1980, inquiries: 38, percentage: 12.6 },
    { region: 'Others', products: 3, views: 2290, inquiries: 32, percentage: 14.6 },
  ],
};

// Mock products data
export const mockProducts: IProduct[] = [
  {
    id: 'p1',
    title: 'iPhone 13 Pro - 128GB Unlocked',
    price: 4500.00,
    originalPrice: 5200.00,
    image: 'https://picsum.photos/300/300?random=1',
    category: 'phones',
    status: 'active',
    condition: 'new',
    stockCount: 3,
    views: 1250,
    favorites: 89,
    sales: 2,
    revenue: 9000.00,
    rating: 4.8,
    reviews: 12,
    dateCreated: '2024-05-25',
    lastUpdated: '2 hours ago',
    isPromoted: true,
    isDraft: false,
    tags: ['premium', 'latest', 'authentic'],
  },
  {
    id: 'p2',
    title: 'AirPods Pro (2nd Gen) - Authentic',
    price: 1200.00,
    originalPrice: 1400.00,
    image: 'https://picsum.photos/300/300?random=2',
    category: 'accessories',
    status: 'active',
    condition: 'new',
    stockCount: 8,
    views: 890,
    favorites: 45,
    sales: 5,
    revenue: 6000.00,
    rating: 4.6,
    reviews: 8,
    dateCreated: '2024-05-20',
    lastUpdated: '1 day ago',
    isPromoted: false,
    isDraft: false,
    tags: ['trending', 'authentic'],
  },
  {
    id: 'p3',
    title: 'MacBook Air M2 - 256GB Silver',
    price: 8500.00,
    image: 'https://picsum.photos/300/300?random=3',
    category: 'laptops',
    status: 'out_of_stock',
    condition: 'new',
    stockCount: 0,
    views: 2100,
    favorites: 156,
    sales: 1,
    revenue: 8500.00,
    rating: 4.9,
    reviews: 3,
    dateCreated: '2024-05-15',
    lastUpdated: '3 days ago',
    isPromoted: true,
    isDraft: false,
    tags: ['premium', 'apple', 'laptop'],
  },
  {
    id: 'p4',
    title: 'Samsung Galaxy S24 Ultra Draft',
    price: 5200.00,
    image: 'https://picsum.photos/300/300?random=4',
    category: 'phones',
    status: 'draft',
    condition: 'new',
    stockCount: 2,
    views: 0,
    favorites: 0,
    sales: 0,
    revenue: 0,
    rating: 0,
    reviews: 0,
    dateCreated: '2024-05-28',
    lastUpdated: '30 mins ago',
    isPromoted: false,
    isDraft: true,
    tags: ['samsung', 'flagship'],
  },
  {
    id: 'p5',
    title: 'Gaming Chair RGB - Ergonomic',
    price: 850.00,
    originalPrice: 950.00,
    image: 'https://picsum.photos/300/300?random=5',
    category: 'furniture',
    status: 'paused',
    condition: 'like-new',
    stockCount: 5,
    views: 420,
    favorites: 23,
    sales: 0,
    revenue: 0,
    rating: 4.2,
    reviews: 2,
    dateCreated: '2024-05-10',
    lastUpdated: '1 week ago',
    isPromoted: false,
    isDraft: false,
    tags: ['gaming', 'furniture'],
  },
];

export const introData: IIntroSlide[] = [
  {
    id: 1,
    title: 'Welcome to Peyba',
    subtitle: 'The Future of Mobile Money',
    description: 'Experience a revolutionary way to manage your mobile money transactions with cutting-edge technology.',
    icon: 'rocket-launch',
    gradient: ['#FF6B6B', '#4ECDC4'],
    pattern: 'circles',
  },
  {
    id: 2,
    title: 'Smart & Secure',
    subtitle: 'Your Money, Protected',
    description: 'Bank-level security meets intuitive design. Track every cedi with confidence and ease.',
    icon: 'security',
    gradient: ['#667eea', '#764ba2'],
    pattern: 'waves',
  },
  {
    id: 3,
    title: 'Join Thousands',
    subtitle: 'Be Part of the Revolution',
    description: 'Connect with a growing network of users and agents. Your financial journey starts here.',
    icon: 'people',
    gradient: ['#f093fb', '#f5576c'],
    pattern: 'dots',
  },
];

// Enhanced notifications data
export const dummyNotifications: INotification[] = [
  {
    id: 'n1',
    type: 'follow',
    title: 'New Follower',
    message: 'Emma Wilson started following you',
    avatar: 'https://i.pravatar.cc/150?img=19',
    timestamp: new Date(Date.now() - 5 * 60 * 1000),
    isRead: false,
    actionRequired: true,
    actionType: 'follow_back',
    userId: 'f1',
    userName: 'Emma Wilson',
    userVerified: true,
  },
  {
    id: 'n2',
    type: 'transaction',
    title: 'Payment Received',
    message: 'You received GH₵ 250.00 from James Miller',
    avatar: 'https://i.pravatar.cc/150?img=22',
    timestamp: new Date(Date.now() - 15 * 60 * 1000),
    isRead: false,
    actionRequired: false,
    amount: 250.00,
    transactionId: 'TXN123456789',
    transactionType: 'credit',
  },
  {
    id: 'n3',
    type: 'like',
    title: 'Post Liked',
    message: 'Sophie Chen and 12 others liked your post',
    avatar: 'https://i.pravatar.cc/150?img=31',
    timestamp: new Date(Date.now() - 45 * 60 * 1000),
    isRead: true,
    actionRequired: false,
    postImage: 'https://picsum.photos/300/200?random=1',
    likesCount: 13,
    postTitle: 'Beautiful sunset from the rooftop',
  },
  {
    id: 'n4',
    type: 'comment',
    title: 'New Comment',
    message: 'David Brown commented on your post: "Amazing shot! 📸"',
    avatar: 'https://i.pravatar.cc/150?img=14',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
    isRead: true,
    actionRequired: true,
    actionType: 'reply',
    postImage: 'https://picsum.photos/300/200?random=2',
    commentText: 'Amazing shot! 📸',
  },
  {
    id: 'n5',
    type: 'system',
    title: 'Account Verification',
    message: 'Your account has been successfully verified! You now have access to premium features.',
    icon: 'verified',
    timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000),
    isRead: false,
    actionRequired: true,
    actionType: 'explore_features',
    priority: 'high',
  },
  {
    id: 'n6',
    type: 'agent',
    title: 'New Agent Nearby',
    message: 'Quick Cash Services is now available 0.3km from your location',
    avatar: 'https://i.pravatar.cc/150?img=40',
    timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000),
    isRead: true,
    actionRequired: true,
    actionType: 'view_agent',
    agentName: 'Quick Cash Services',
    distance: '0.3km',
    rating: 4.8,
  },
  {
    id: 'n7',
    type: 'transaction',
    title: 'Payment Sent',
    message: 'You sent GH₵ 150.00 to Maria Garcia',
    avatar: 'https://i.pravatar.cc/150?img=52',
    timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000),
    isRead: true,
    actionRequired: false,
    amount: 150.00,
    transactionId: 'TXN987654321',
    transactionType: 'debit',
  },
  {
    id: 'n8',
    type: 'promotion',
    title: 'Special Offer',
    message: 'Get 20% bonus on all mobile money transactions this weekend!',
    icon: 'local-offer',
    timestamp: new Date(Date.now() - 26 * 60 * 60 * 1000),
    isRead: false,
    actionRequired: true,
    actionType: 'claim_offer',
    discount: '20%',
    validUntil: 'Sunday, 11:59 PM',
    priority: 'medium',
  },
  {
    id: 'n9',
    type: 'security',
    title: 'Login Alert',
    message: 'New login detected from iPhone in Accra, Ghana',
    icon: 'security',
    timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    isRead: true,
    actionRequired: true,
    actionType: 'review_security',
    location: 'Accra, Ghana',
    device: 'iPhone 14 Pro',
  },
  {
    id: 'n10',
    type: 'achievement',
    title: 'Achievement Unlocked',
    message: 'Congratulations! You\'ve completed 100 successful transactions',
    icon: 'emoji-events',
    timestamp: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    isRead: true,
    actionRequired: false,
    achievementName: 'Transaction Master',
    rewardPoints: 500,
  },
  {
    id: 'n11',
    type: 'follow',
    title: 'Friend Joined',
    message: 'Alex Johnson joined the platform and is now following you',
    avatar: 'https://i.pravatar.cc/150?img=16',
    timestamp: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    isRead: true,
    actionRequired: false,
    userId: 'f6',
    userName: 'Alex Johnson',
    userVerified: false,
  },
  {
    id: 'n12',
    type: 'update',
    title: 'App Update Available',
    message: 'Version 2.1.0 is now available with new features and improvements',
    icon: 'system-update',
    timestamp: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    isRead: true,
    actionRequired: true,
    actionType: 'update_app',
    version: '2.1.0',
    features: ['Enhanced Security', 'New UI', 'Bug Fixes'],
  },
];
