import { IProduct } from "../types/agentProductTypes";

export const mockProducts: IProduct[] = [
  {
    id: '1',
    title: 'iPhone 15 Pro Max 256GB Natural Titanium',
    price: 4500,
    originalPrice: 5000,
    image: 'https://picsum.photos/400/400?random=1',
    status: 'active',
    views: 1250,
    sales: 8,
    revenue: 36000,
    favorites: 45,
    stockCount: 5,
    tags: ['smartphone', 'apple', 'premium', 'latest'],
    isPromoted: true,
    dateCreated: '2024-01-15',
    lastUpdated: '2 days ago',
  },
  {
    id: '2',
    title: 'MacBook Air M3 13-inch 512GB Space Gray',
    price: 7200,
    image: 'https://picsum.photos/400/400?random=2',
    status: 'active',
    views: 890,
    sales: 3,
    revenue: 21600,
    favorites: 28,
    stockCount: 2,
    tags: ['laptop', 'apple', 'macbook', 'productivity'],
    isPromoted: false,
    dateCreated: '2024-01-10',
    lastUpdated: '1 week ago',
  },
  {
    id: '3',
    title: 'Samsung Galaxy S24 Ultra 512GB Titanium Black',
    price: 4200,
    originalPrice: 4800,
    image: 'https://picsum.photos/400/400?random=3',
    status: 'draft',
    views: 0,
    sales: 0,
    revenue: 0,
    favorites: 0,
    stockCount: 3,
    tags: ['smartphone', 'samsung', 'android', 'premium'],
    isPromoted: false,
    dateCreated: '2024-01-20',
    lastUpdated: '5 hours ago',
  },
  {
    id: '4',
    title: 'Sony WH-1000XM5 Wireless Noise Canceling Headphones',
    price: 1200,
    image: 'https://picsum.photos/400/400?random=4',
    status: 'active',
    views: 450,
    sales: 12,
    revenue: 14400,
    favorites: 67,
    stockCount: 8,
    tags: ['headphones', 'sony', 'wireless', 'noise-canceling'],
    isPromoted: true,
    dateCreated: '2024-01-05',
    lastUpdated: '3 days ago',
  },
  {
    id: '5',
    title: 'iPad Pro 12.9-inch M4 256GB Space Black',
    price: 5500,
    image: 'https://picsum.photos/400/400?random=5',
    status: 'paused',
    views: 320,
    sales: 2,
    revenue: 11000,
    favorites: 15,
    stockCount: 1,
    tags: ['tablet', 'apple', 'ipad', 'creative'],
    isPromoted: false,
    dateCreated: '2024-01-12',
    lastUpdated: '1 day ago',
  },
  {
    id: '6',
    title: 'Dell XPS 15 Intel i7 16GB RAM 1TB SSD',
    price: 6800,
    originalPrice: 7500,
    image: 'https://picsum.photos/400/400?random=6',
    status: 'out_of_stock',
    views: 180,
    sales: 1,
    revenue: 6800,
    favorites: 9,
    stockCount: 0,
    tags: ['laptop', 'dell', 'windows', 'performance'],
    isPromoted: false,
    dateCreated: '2024-01-08',
    lastUpdated: '2 weeks ago',
  },
  {
    id: '7',
    title: 'Apple Watch Series 9 45mm GPS + Cellular',
    price: 2200,
    image: 'https://picsum.photos/400/400?random=7',
    status: 'active',
    views: 680,
    sales: 6,
    revenue: 13200,
    favorites: 34,
    stockCount: 4,
    tags: ['smartwatch', 'apple', 'fitness', 'health'],
    isPromoted: false,
    dateCreated: '2024-01-18',
    lastUpdated: '4 days ago',
  },
  {
    id: '8',
    title: 'AirPods Pro 2nd Generation USB-C',
    price: 950,
    originalPrice: 1100,
    image: 'https://picsum.photos/400/400?random=8',
    status: 'active',
    views: 920,
    sales: 15,
    revenue: 14250,
    favorites: 78,
    stockCount: 12,
    tags: ['earbuds', 'apple', 'wireless', 'noise-canceling'],
    isPromoted: true,
    dateCreated: '2024-01-03',
    lastUpdated: '6 hours ago',
  },
  {
    id: '9',
    title: 'Nintendo Switch OLED Model White',
    price: 1800,
    image: 'https://picsum.photos/400/400?random=9',
    status: 'draft',
    views: 0,
    sales: 0,
    revenue: 0,
    favorites: 0,
    stockCount: 2,
    tags: ['gaming', 'nintendo', 'console', 'portable'],
    isPromoted: false,
    dateCreated: '2024-01-22',
    lastUpdated: '2 hours ago',
  },
  {
    id: '10',
    title: 'Canon EOS R8 Mirrorless Camera Body',
    price: 8500,
    image: 'https://picsum.photos/400/400?random=10',
    status: 'active',
    views: 125,
    sales: 1,
    revenue: 8500,
    favorites: 18,
    stockCount: 1,
    tags: ['camera', 'canon', 'photography', 'mirrorless'],
    isPromoted: false,
    dateCreated: '2024-01-14',
    lastUpdated: '1 week ago',
  },
];